### PR TITLE
Remove SignalProducer.buffer usage

### PR DESCRIPTION
**Pull request by ikesyo**
With regard to https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2831.

### CODE REVIEW

**Comment by mdiep** [comment]
Looks good. 👍 

I really hate this bit of code.

**Comment by ikesyo** [comment]
> I really hate this bit of code.

I agree. This looks a bit ugly. :disappointed:

**Comment by mdiep** [comment]
It was ugly before. That wasn't a condemnation of your changes her. 😄

**Comment by ikesyo** [comment]
Oh, that was my misunderstanding. ☺️

**Pull request merged**
