### PR TITLE
Add waitForAllTaskTermination for fixing segmentation fault of Carthage

### PR DESCRIPTION
**Pull request by norio-nomura**
*This is rebased version of #21.*

Fix segmentation fault on termination of Carthage.

Segmentation fault on termination of Carthage 0.7.4 beta-2 happens following scenario:
1. launchTask's thread call `sendCompleted()` and kick main thread
2a. main thread wake up and call `exit()`
2b. launchTask's thread continue disposing
3. main thread cause segmentation fault.

Waiting `completed` from launchTask's thread is not enough for fixing the segmentation fault.
It needs waiting actual termination of launchTask's thread

https://github.com/Carthage/Carthage/pull/474#issuecomment-107949958

### CODE REVIEW

**Comment by robrix** [comment]
It looks like @jspahrsummers left some feedback on #21. Could you that feedback on this PR please?

**Comment by norio-nomura** [comment]
Thanks for reviewing.
As @jspahrsummers wrote on https://github.com/Carthage/ReactiveTask/pull/21#issuecomment-106157870, his comments on lines are not valuable for the purpose of this PR.
He implemented #23 from my suggestion by #21, using fine-grained and waiting per-task logic using RAC way. But #23 did not be replacement of #21.
So, I push this PR.

**Comment by robrix** [comment]
Okay, thanks for the info. I think given the practical considerations that we ought to merge this PR, and then if it needs adjustment we can do that later on.

Thanks very much for the PR and your investigation into the segfaults, @norio-nomura!

**Comment by norio-nomura** [comment]
Thank you for reviewing & merging it.

I have one more https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2058 related to Carthage hangs. I wish it will be also merged to next release.

**Comment by robrix** [comment]
Cool, merged.

**Comment by norio-nomura** [comment]
Thanks!

**Comment by norio-nomura** [comment]
Oh, I should said about ReactiveCocoa before I pushed update `Cartfile`, Sorry. :pensive:

**Comment by robrix** [comment]
Don’t sweat it!

**Comment by norio-nomura** [comment]
Thanks,
I don't have any pending PRs about Carthage.

**Pull request merged**
