### PR TITLE
Add playground to the workspace

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by mdiep** [comment]
What's the value in adding this to the workplace?

**Comment by ikesyo** [comment]
IIUC we need adding it to the workspace to use custom frameworks.

**Comment by ikesyo** [comment]
Motivation: I wanted to make it sure that the code example in README should work correctly.

**Comment by mdiep** [comment]
I'm not sure it makes sense to add this to the repository. If you want to test out other changes, you'll need to revert them or not add them when you commit. IMO it's not any harder to do that than to revert or not commit the addition of the playground to the workspace.

**Comment by ikesyo** [comment]
Thanks for the comment. It's okay, I don't have no compelling reason to add this now. Closing this. :relaxed:

**Pull request closed without merging**
